-- Run this script in your Supabase SQL Editor to create the necessary tables

CREATE TABLE IF NOT EXISTS public.profiles (
    id TEXT PRIMARY KEY,
    name TEXT,
    url TEXT,
    description TEXT,
    bio TEXT,
    location TEXT,
    phone TEXT,
    email TEXT,
    whatsapp TEXT,
    endowment TEXT,
    age TEXT,
    height TEXT,
    weight TEXT,
    nationality TEXT,
    languages TEXT,
    cam_chat TEXT,
    onlyfans TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

CREATE TABLE IF NOT EXISTS public.photos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id TEXT REFERENCES public.profiles(id) ON DELETE CASCADE,
    photo_url TEXT,
    local_path TEXT
);

CREATE TABLE IF NOT EXISTS public.services (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id TEXT REFERENCES public.profiles(id) ON DELETE CASCADE,
    service_name TEXT,
    available BOOLEAN
);

-- Enable Row Level Security (RLS) but allow anonymous reads and service role writes
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.photos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.services ENABLE ROW LEVEL SECURITY;

-- Policies for public reading
CREATE POLICY "Allow public read access on profiles" ON public.profiles FOR SELECT USING (true);
CREATE POLICY "Allow public read access on photos" ON public.photos FOR SELECT USING (true);
CREATE POLICY "Allow public read access on services" ON public.services FOR SELECT USING (true);

-- Allow full access for service_role (which we use in the backend)
-- No explicit policy needed for service_role as it bypasses RLS automatically, 
-- but we can add policies for anon to insert if we wanted. Since our API uses anon key for now (from frontend) or service_role from backend, we will just allow all for simplicity in this MVP, or stick to service_role for writes.
CREATE POLICY "Allow all access for anon" ON public.profiles FOR ALL USING (true);
CREATE POLICY "Allow all access for anon" ON public.photos FOR ALL USING (true);
CREATE POLICY "Allow all access for anon" ON public.services FOR ALL USING (true);
